### ISSUE TITLE
No module named lib2to3.pgen2.parse

### ISSUE THREAD

**Issue by ruckusdc** [cytech/weather.wundergroundpws#3]
Hi,

Thank you so much for doing this for us PWS owners, I really want to use this addon. However I get the following error in my log file...
Error Type: <type 'exceptions.ImportError'>
                                            Error Contents: No module named lib2to3.pgen2.parse
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/weather.wundergroundpws/default.py", line 43, in <module>
                                                from past.utils import old_div
                                              File "/storage/.kodi/addons/script.module.future/libs/past/__init__.py", line 88, in <module>
                                                from past.translation import install_hooks as autotranslate
                                              File "/storage/.kodi/addons/script.module.future/libs/past/translation/__init__.py", line 41, in <module>
                                                from lib2to3.pgen2.parse import ParseError
                                            ImportError: No module named lib2to3.pgen2.parse
                                            -->End of Python script error report<--

**Comment by cytech** [comment]
What version of Kodi ?
Did you install the addon thru  Kodi - System - Addons - Install from Zip File ?

**Comment by ruckusdc** [comment]
Libreelec leia 18.1
and yeah i downloaded the zip and installed it like that

**Comment by cytech** [comment]
can you check your .kodi/addons directory and see if there is an addon named "script.module.future".
If not it needs to be installed from "https://mirrors.kodi.tv/addons/leia/script.module.future/script.module.future-0.16.0.4.zip"
the dependency should have been installed when you installed the weather.wundergroundpws addon.

**Comment by ruckusdc** [comment]
Hi.

Again thanks for your support and help. "script.module.future" was installed but I reinstalled it from the link you provided to see if it was missing something or out of date.

Sorry, same exact error message and I did reboot the box too.

**Comment by cytech** [comment]
it looks like libelec does not include  the python lib2to3 module
https://forum.libreelec.tv/thread/14994-problem-with-python-lib2to3-missing-google-music-exp/

**Comment by ruckusdc** [comment]
ok well that sucks. thanks for your efforts.

**Comment by Megachip** [comment]
> can you check your .kodi/addons directory and see if there is an addon named "script.module.future".
> If not it needs to be installed from "https://mirrors.kodi.tv/addons/leia/script.module.future/script.module.future-0.16.0.4.zip"
> the dependency should have been installed when you installed the weather.wundergroundpws addon.
Can you fix the depency? running into the same problem:

```
2019-05-27 17:59:28.645 T:959656816   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ImportError'>
                                            Error Contents: No module named lib2to3.pgen2.parse
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/weather.wundergroundpws/default.py", line 43, in <module>
                                                from past.utils import old_div
                                              File "/storage/.kodi/addons/script.module.future/libs/past/__init__.py", line 88, in <module>
                                                from past.translation import install_hooks as autotranslate
                                              File "/storage/.kodi/addons/script.module.future/libs/past/translation/__init__.py", line 41, in <module>
                                                from lib2to3.pgen2.parse import ParseError
                                            ImportError: No module named lib2to3.pgen2.parse
                                            -->End of Python script error report<--
```
version="0.16.0.4" is installed :/

**Comment by Megachip** [comment]
https://forum.kodi.tv/showthread.php?tid=200640&pid=2842804#pid2842804 describes a workaround
