### ISSUE TITLE
Weather UndergroundPWS Error

### ISSUE THREAD

**Issue by mfreeman72** [cytech/weather.wundergroundpws#6]
I've set up my weather station sensors and they are registered to my Weather Underground API key. However, I cannot connect properly to the station from your addon. It will sometimes show the weather data, although it gives an error every time I refresh the data, but sometimes it doesn't, especially after a reboot. I have the correct API key, Display Name, Station ID, and Lat/Long entered. I'm running Kodi 18.7 on my Raspberry Pi with OSMC.

In the Kodi logs, the only thing related to this that I can find are as follows:

2020-06-03 12:50:47.353 T:1282106080   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: unsupported operand type(s) for -: 'unicode' and 'float'
                                            Traceback (most recent call last):
                                              File "/home/osmc/.kodi/addons/weather.wundergroundpws/default.py", line 316, in <module>
                                                forecast(location, locationid, locationlat, locationlon)
                                              File "/home/osmc/.kodi/addons/weather.wundergroundpws/default.py", line 125, in forecast
                                                properties(data,loc,locid)
                                              File "/home/osmc/.kodi/addons/weather.wundergroundpws/default.py", line 164, in properties
                                                set_property('Current.WindDirection' , str(wind_deg_to_card(data['observations'][0]['winddir'])))
                                              File "/home/osmc/.kodi/addons/weather.wundergroundpws/resources/lib/utilities.py", line 230, in wind_deg_to_card
                                                return arr[int(abs((deg - 11.25) % 360) / 22.5)]
                                            TypeError: unsupported operand type(s) for -: 'unicode' and 'float'
                                            -->End of Python script error report<--

**Comment by mfreeman72** [comment]
Additional info: When looking at the weather info, everything seems correct, except the humidity. It shows a different value than it should (my PWS's web dashboard shows 33%, while Kodi shows 19%%%...), and every time it refreshes, it adds another % sign, so that eventually you can only see a row of % signs because the number has moved outside the viewable screen area. I don't know if the wind speed or rain totals work properly, as I don't yet have sensors for those, and they both show 0 mph and 0%, respectively.

**Comment by cytech** [comment]
when wunderground api is not reporting properly you will see those issues with percent sign.
i need to put in error checks for when this happens but don't have the time right now.
once the api starts reporting correctly the error goes away.

for the forecast, the data is retrieved from the latitude/longitude so changing these to your closest "big city" seems to help.  also note that if the lat/lon is over a body of water (or close enough to it) the api will fail

**Comment by mfreeman72** [comment]
The forecast seems fine. I've also noticed that sometimes, it just stops updating altogether. It will be correct at first, then will stay at that temperature hours after my PWS has reported different temperatures, until I manually update it. This is not always the case, just sometimes. I'm assuming it's related to the issue of sometimes not showing weather data at all when refreshed.

As far as the lat/lon location, we live in a heavily agricultural area with canals and ponding basins, but otherwise, we're miles from any significant bodies of water. So unless the canal and ponding basin near my house is causing a problem, I don't think there should be any issues with lat/lon.

**Comment by cytech** [comment]
no,body of water being large (lake or ocean) per wunderground api docs.

every time i run into an issue  with the kodi addon like you are describing, it has been wunderground api is down, not reporting, etc, etc
just 2 days ago the api was not accepting requests from my weewx upload and the percent signs and an outdoor temperature of 728 degrees was reported in kodi.
8 hours later it was back to normal
